"""empty message

Revision ID: 1c5a42be4a07
Revises: f912a8c96173
Create Date: 2019-09-07 10:14:07.707017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c5a42be4a07'
down_revision = 'f912a8c96173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status', sa.Column('name', sa.Enum('not delayed', 'delayed')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('status', 'name')
    # ### end Alembic commands ###
