"""empty message

Revision ID: 8117c2e39c0b
Revises: 1c5a42be4a07
Create Date: 2019-09-07 14:13:34.930256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8117c2e39c0b'
down_revision = '1c5a42be4a07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line', sa.Column('down_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('line', 'down_time')
    # ### end Alembic commands ###
